version: "3.9"
services:
    django:
        container_name: app
        image:  netthands_web_site_and_portal:latest
        volumes:
            - static:/staticfiles/
        env_file:
            - .env
        build:
            context: . 
        ports:
            - "8000:8000"
    nginx:
        container_name: nginx
        image: netthandshomecare-nginx:latest
        volumes:
            - static:/staticfiles/
        build: ./nginx
        ports:
            - "80:80"
        restart: "unless-stopped"
        
    db:
        image: postgres
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
                - postgres:/data
volumes:
    static:
    postgres: 