# Generated by Django 4.2.2 on 2023-06-25 18:19
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("X", "Non-Gendered"),
                    ("B", "Binary"),
                ],
                default="X",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="in_compliance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="social_security",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(999999999)],
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="state",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="street_address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="zipcode",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(99999)],
            ),
        ),
    ]
