# Generated by Django 4.2.2 on 2023-07-02 17:08

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[("A", "Active"), ("T", "Terminated")],
                default="A",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="in_compliance",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="social_security",
            field=localflavor.us.models.USSocialSecurityNumberField(
                max_length=11, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="state",
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="street_address",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="zipcode",
            field=localflavor.us.models.USZipCodeField(max_length=10, null=True),
        ),
    ]
