# Generated by Django 4.2.2 on 2023-07-10 23:28

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_first_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_last_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="US"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("X", "Non-Gendered"),
                    ("B", "Binary"),
                ],
                default="X",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="social_security",
            field=localflavor.us.models.USSocialSecurityNumberField(
                blank=True, max_length=11, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="street_address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
