# Generated by Django 4.2.2 on 2023-07-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_employee_phone_alter_employee_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(null=True),
        ),
    ]
