# Generated by Django 4.2.2 on 2023-07-11 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_alter_employee_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="ethnicity",
            field=models.CharField(blank=True, default="REFUSED", max_length=255),
        ),
        migrations.CreateModel(
            name="InServiceTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
