# Generated by Django 4.2.2 on 2023-07-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_employee_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="job_title",
            field=models.CharField(null=True),
        ),
    ]
