# Generated by Django 4.2.2 on 2023-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_employee_ethnicity_inservicetraining"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLACK", "Black/African American"),
                    ("NATIVE", "American Indian/Alaska Native"),
                    ("ASIAN", "Asian"),
                    ("HAWAIIAN", "Native Hawaiian/Other Pacific Islander"),
                    ("WHITE", "White/Caucasian"),
                    ("OTHER", "Other Race"),
                    ("BI_RACIAL", "Two or More Races"),
                    ("UNKNOWN", "Unknown"),
                    ("REFUSED", "Perfer Not To Disclose"),
                ],
                default="UNKNOWN",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NON-HISPANIC", "Non-Hispanic/Latino"),
                    ("HISPANIC", "Hispanic/Latino"),
                    ("UNKNOWN", "Unknown"),
                    ("REFUSED", "Perfer Not To Disclose"),
                ],
                default="UNKNOWN",
                max_length=255,
            ),
        ),
    ]
