# Generated by Django 4.2.2 on 2023-07-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_employee_race_alter_employee_ethnicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="aps_check_passed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="aps_check_verification",
            field=models.FileField(blank=True, null=True, upload_to="verifications"),
        ),
        migrations.AddField(
            model_name="employee",
            name="cpr_verification",
            field=models.FileField(blank=True, null=True, upload_to="verifications"),
        ),
        migrations.AddField(
            model_name="employee",
            name="family_hca",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="hhs_oig_exclusionary_check_completed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="hhs_oig_exclusionary_check_verification",
            field=models.FileField(blank=True, null=True, upload_to="verifications"),
        ),
        migrations.AddField(
            model_name="employee",
            name="idph_background_check_completed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="idph_background_check_verification",
            field=models.FileField(blank=True, null=True, upload_to="verifications"),
        ),
        migrations.AddField(
            model_name="employee",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENGLISH", "English"),
                    ("CHINESE", "Ethnic Chinese"),
                    ("GREEK", "Greek"),
                    ("ITALIAN", "Italian"),
                    ("LAOTIAN", "Laotian"),
                    ("ROMANIAN", "Romanian"),
                    ("TAGALOG", "Tagalog"),
                    ("YIDDISH", "Yiddish"),
                    ("ARABIC", "Arabic"),
                    ("FARSI", "Farsi"),
                    ("GUJARATI", "Gujarati"),
                    ("JAPANESE", "Japanese"),
                    ("LITHUANIAN", "Lithuanian"),
                    ("RUSSIAN", "Russian"),
                    ("UKRANIAN", "Ukranian"),
                    ("YUGOSLAVIAN", "Yugoslavian"),
                    ("ASSYRIAN", "Assyrian"),
                    ("FRENCH", "French"),
                    ("CREOLE", "Haitian Creole"),
                    ("MON-KHMER", "Mon-Khmer"),
                    ("MANDARIN", "Mandarin"),
                    ("SPANISH", "Spanish"),
                    ("URDU", "Urdu"),
                    ("CANTONESE", "Cantonese"),
                    ("GERMAN", "German"),
                    ("HINDI", "Hindi"),
                    ("KOREAN", "Korean"),
                    ("POLISH", "Polish"),
                    ("SWEDISH", "Swedish"),
                    ("VIETNAMESE", "Vietnamese"),
                ],
                default="ENGLISH",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="pre_training_verification",
            field=models.FileField(blank=True, null=True, upload_to="verifications"),
        ),
        migrations.AddField(
            model_name="employee",
            name="qualifications",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HIGH_SCHOOL_GED", "High School Diploma/GED"),
                    ("CNA", "Certified Nursing Assistant (CNA)"),
                    ("LPN", "LPN"),
                    ("RN", "Registered Nurse (RN)"),
                    ("EXPERIENCE", "Applicable Experience"),
                    ("BACHELORS", "Bachelor's degree"),
                    ("MASTERS", "Master’s degree and above"),
                    ("O", "Other"),
                ],
                default="HIGH_SCHOOL_GED",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="qualifications_verification",
            field=models.FileField(blank=True, null=True, upload_to="verifications"),
        ),
        migrations.AddField(
            model_name="employee",
            name="training_exempt",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AIDE", "Homecare Aide"),
                    ("CARE_COORDINATOR", "Care Coordinator"),
                    ("CARE_COORDINATOR_SUPERVISOR", "Care Coordinator Supervisor"),
                    ("HOMECARE_SUPERVISOR", "Homecare Supervisor"),
                ],
                default="AIDE",
                max_length=255,
                null=True,
            ),
        ),
    ]
