# Generated by Django 4.2.2 on 2023-07-03 10:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_employee_pre_service_completion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="pre_service_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
