# Generated by Django 4.2.2 on 2023-07-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_employee_aps_check_passed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="fingerprint_criminal_background_check_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
