# Generated by Django 4.2.2 on 2023-07-12 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "portal",
            "0006_employee_fingerprint_criminal_background_check_completion_date",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="fingerprint_criminal_background_check_completion_date",
            new_name="idph_background_check_completion_date",
        ),
    ]
