# Generated by Django 4.2.2 on 2023-07-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portal",
            "0007_rename_fingerprint_criminal_background_check_completion_date_employee_idph_background_check_completi",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NON-HISPANIC", "Non-Hispanic/Latino"),
                    ("HISPANIC", "Hispanic/Latino"),
                    ("UNKNOWN", "Unknown"),
                    ("REFUSED", "Perfer Not To Disclose"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
