# Generated by Django 4.2.2 on 2023-07-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0010_alter_employee_contract_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_of_bith",
            field=models.DateField(blank=True, null=True),
        ),
    ]
