# Generated by Django 4.2.2 on 2023-07-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0011_employee_date_of_bith"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="date_of_bith",
            new_name="date_of_birth",
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(auto_now=True),
        ),
    ]
