# Generated by Django 4.2.2 on 2023-07-01 15:01
import localflavor.us.models
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientInterestSubmissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="US",
                    ),
                ),
                ("zipcode", localflavor.us.models.USZipCodeField(max_length=10)),
                ("insurance_carrier", models.CharField(max_length=255)),
                (
                    "desired_service",
                    models.CharField(
                        choices=[
                            ("I", "Intermittent Home Care"),
                            ("NM", "Non-Medical Home Care"),
                            ("MSW", "Medical Social Work"),
                            ("OT", "Occupational Therapy"),
                            ("PT", "Physical Therapy"),
                            ("NA", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Interested Client",
                "verbose_name_plural": "Interested Clients",
                "db_table": "interest_clients",
                "ordering": ["last_name", "first_name", "date_submitted"],
            },
        ),
        migrations.CreateModel(
            name="EmploymentApplicationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="US",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("home_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", localflavor.us.models.USStateField(max_length=2)),
                ("zipcode", localflavor.us.models.USZipCodeField(max_length=10)),
                (
                    "mobility",
                    models.CharField(
                        choices=[
                            ("C", "I Have Consistent Access To A Car"),
                            ("P", "I Use Public Transportation"),
                            (
                                "RS",
                                "I Use Rideshare (Uber/Lyft) or a Reliable Pickup/Dropoff Provider",
                            ),
                            ("NA", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "prior_experience",
                    models.CharField(
                        choices=[
                            ("S", "12+ Months"),
                            ("J", "3+ Months"),
                            ("N", "No Prior Experience"),
                        ],
                        max_length=255,
                    ),
                ),
                ("ipdh_registered", models.BooleanField(default=False)),
                ("availability_monday", models.BooleanField()),
                ("availability_tuesday", models.BooleanField()),
                ("availability_wednesday", models.BooleanField()),
                ("availability_thursday", models.BooleanField()),
                ("availability_friday", models.BooleanField()),
                ("availability_saturday", models.BooleanField()),
                ("availability_sunday", models.BooleanField()),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prospective Employee",
                "verbose_name_plural": "Prospective Employees",
                "db_table": "employment_interests",
                "ordering": ["last_name", "first_name", "date_submitted"],
            },
        ),
    ]
