# Generated by Django 4.2.2 on 2023-06-29 14:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinterestsubmissions",
            name="desired_service",
            field=models.CharField(
                choices=[
                    ("I", "Intermittent Home Care"),
                    ("NM", "Non-Medical Home Care"),
                    ("MSW", "Medical Social Work"),
                    ("OT", "Occupational Therapy"),
                    ("PT", "Physical Therapy"),
                    ("NA", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
