# Generated by Django 4.2.2 on 2023-07-10 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentapplicationmodel",
            name="hired",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="employmentapplicationmodel",
            name="reviewed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="employmentapplicationmodel",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="availability_friday",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="availability_monday",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="availability_saturday",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="availability_sunday",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="availability_thursday",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="availability_tuesday",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employmentapplicationmodel",
            name="availability_wednesday",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
