# Generated by Django 4.2.2 on 2023-06-29 14:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_clientinterestsubmissions_desired_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinterestsubmissions",
            name="email",
            field=models.EmailField(default="none@none.com", max_length=254, null=True),
        ),
    ]
