# Generated by Django 4.2.2 on 2023-06-29 15:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_clientinterestsubmissions_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinterestsubmissions",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
